In [1]:
import pandas as pd
import geopandas as gpd
import folium
import branca.colormap as cm
from folium.features import GeoJsonTooltip

In [3]:
path_csv_data = 'usa_population_2019.csv'
population_data = pd.read_csv(path_csv_data)

In [4]:
population_data.head(10)

  Geographic Area Postal Code  Total Resident Population
0   United States         NaN                  328239523
1       Northeast         NaN                   55982803
2         Midwest         NaN                   68329004
3           South         NaN                  125580448
4            West         NaN                   78347268
5         Alabama          AL                    4903185
6          Alaska          AK                     731545
7         Arizona          AZ                    7278717
8        Arkansas          AR                    3017804
9      California          CA                   39512223

In [5]:
population_json_data = 'us-states.json'
gdf = gpd.read_file(population_json_data)

In [6]:
gdf.head()

   id        name                                           geometry
0  AL     Alabama  POLYGON ((-87.35930 35.00118, -85.60667 34.984...
1  AK      Alaska  MULTIPOLYGON (((-131.60202 55.11798, -131.5691...
2  AZ     Arizona  POLYGON ((-109.04250 37.00026, -109.04798 31.3...
3  AR    Arkansas  POLYGON ((-94.47384 36.50186, -90.15254 36.496...
4  CA  California  POLYGON ((-123.23326 42.00619, -122.37885 42.0...

In [11]:
gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [7]:
mereged_data = gdf.merge(population_data, left_on='name', right_on='Geographic Area')
mereged_data.head()

,id,name,geometry,Geographic Area,Postal Code,Total Resident Population
0,AL,Alabama,"POLYGON ((-87.35930 35.00118, -85.60667 34.984...",Alabama,AL,4903185
1,AK,Alaska,"MULTIPOLYGON (((-131.60202 55.11798, -131.5691...",Alaska,AK,731545
2,AZ,Arizona,"POLYGON ((-109.04250 37.00026, -109.04798 31.3...",Arizona,AZ,7278717
3,AR,Arkansas,"POLYGON ((-94.47384 36.50186, -90.15254 36.496...",Arkansas,AR,3017804
4,CA,California,"POLYGON ((-123.23326 42.00619, -122.37885 42.0...",California,CA,39512223

In [13]:
mereged_data['area_km2'] = mereged_data['geometry'].to_crs(3395).area / 10**6
mereged_data['population_density'] = mereged_data['Total Resident Population'] / mereged_data['area_km2']
mereged_data

,id,name,geometry,Geographic Area,Postal Code,Total Resident Population,area_km2,population_density
0,AL,Alabama,"POLYGON ((-87.35930 35.00118, -85.60667 34.984...",Alabama,AL,4903185,1.889812e+05,25.945364
1,AK,Alaska,"MULTIPOLYGON (((-131.60202 55.11798, -131.5691...",Alaska,AK,731545,8.196423e+06,0.089252
2,AZ,Arizona,"POLYGON ((-109.04250 37.00026, -109.04798 31.3...",Arizona,AZ,7278717,4.325445e+05,16.827672
3,AR,Arkansas,"POLYGON ((-94.47384 36.50186, -90.15254 36.496...",Arkansas,AR,3017804,2.042087e+05,14.778038
4,CA,California,"POLYGON ((-123.23326 42.00619, -122.37885 42.0...",California,CA,39512223,6.470826e+05,61.062102
5,CO,Colorado,"POLYGON ((-107.91973 41.00391, -105.72895 40.9...",Colorado,CO,5758736,4.453843e+05,12.929813
6,CT,Connecticut,"POLYGON ((-73.05353 42.03905, -71.79931 42.022...",Connecticut,CT,3565287,2.298079e+04,155.142087
7,DE,Delaware,"POLYGON ((-75.41409 39.80446, -75.50720 39.683...",Delaware,DE,973764,8.403159e+03,115.880709
8,FL,Florida,"POLYGON ((-85.49714 30.99754, -85.00421 31.003...",Florida,FL,21477737,1.940085e+05,110.705128
9,GA,Georgia,"POLYGON ((-83.10919 35.00118, -83.32279 34.787...",Georgia,GA,10617423,2.148018e+05,49.428924
10,HI,Hawaii,"MULTIPOLYGON (((-155.63484 18.94827, -155.8813...",Hawaii,HI,1415872,1.664017e+04,85.087574
11,ID,Idaho,"POLYGON ((-116.04751 49.00024, -116.04751 47.9...",Idaho,ID,1787065,4.229594e+05,4.225146
12,IL,Illinois,"POLYGON ((-90.63998 42.51006, -88.78878 42.493...",Illinois,IL,12671821,2.490899e+05,50.872474
13,IN,Indiana,"POLYGON ((-85.99006 41.75972, -84.80704 41.759...",Indiana,IN,6732219,1.586047e+05,42.446538
14,IA,Iowa,"POLYGON ((-91.36842 43.50139, -91.21506 43.501...",Iowa,IA,3155070,2.640713e+05,11.947794
15,KS,Kansas,"POLYGON ((-101.90605 40.00163, -95.30634 40.00...",Kansas,KS,2913314,3.469304e+05,8.397401
16,KY,Kentucky,"POLYGON ((-83.90335 38.76931, -83.67879 38.632...",Kentucky,KY,4467673,1.660861e+05,26.899743
17,LA,Louisiana,"POLYGON ((-93.60849 33.01853, -91.16577 33.002...",Louisiana,LA,4648794,1.658161e+05,28.035845
18,ME,Maine,"POLYGON ((-70.70392 43.05776, -70.82441 43.128...",Maine,ME,1344212,1.709178e+05,7.864670
19,MD,Maryland,"MULTIPOLYGON (((-75.99465 37.95325, -76.01655 ...",Maryland,MD,6045680,4.419879e+04,136.783826
20,MA,Massachusetts,"POLYGON ((-70.91752 42.88797, -70.81894 42.871...",Massachusetts,MA,6892503,3.763784e+04,183.126937
21,MI,Michigan,"MULTIPOLYGON (((-83.45424 41.73234, -84.80704 ...",Michigan,MI,9986857,2.939257e+05,33.977491
22,MN,Minnesota,"POLYGON ((-92.01470 46.70540, -92.09137 46.749...",Minnesota,MN,5639632,4.569895e+05,12.340835
23,MS,Mississippi,"POLYGON ((-88.47111 34.99570, -88.20274 34.995...",Mississippi,MS,2976149,1.743299e+05,17.071937
24,MO,Missouri,"POLYGON ((-91.83396 40.60957, -91.72989 40.615...",Missouri,MO,6137428,2.933137e+05,20.924452
25,MT,Montana,"POLYGON ((-104.04753 49.00024, -104.04206 47.8...",Montana,MT,1068778,8.176207e+05,1.307181
26,NE,Nebraska,"POLYGON ((-103.32458 43.00299, -101.62673 42.9...",Nebraska,NE,1934408,3.566781e+05,5.423400
27,NV,Nevada,"POLYGON ((-117.02788 42.00071, -114.04295 41.9...",Nevada,NV,3080156,4.784663e+05,6.437561
28,NH,New Hampshire,"POLYGON ((-71.08183 45.30330, -71.03254 44.657...",New Hampshire,NH,1359711,4.569876e+04,29.753782
29,NJ,New Jersey,"POLYGON ((-74.23655 41.14083, -73.90245 40.998...",New Jersey,NJ,8882190,3.421552e+04,259.595367
30,NM,New Mexico,"POLYGON ((-107.42133 37.00026, -106.86816 36.9...",New Mexico,NM,2096829,4.620819e+05,4.537786
31,NY,New York,"POLYGON ((-73.34381 45.01303, -73.33285 44.804...",New York,NY,19453561,2.364227e+05,82.282964
32,NC,North Carolina,"POLYGON ((-80.97866 36.56211, -80.29404 36.545...",North Carolina,NC,10488084,1.964801e+05,53.379887
33,ND,North Dakota,"POLYGON ((-97.22874 49.00024, -97.09730 48.682...",North Dakota,ND,762062,3.994357e+05,1.907846
34,OH,Ohio,"POLYGON ((-80.51860 41.97880, -80.51860 40.636...",Ohio,OH,11689100,1.834170e+05,63.729631
35,OK,Oklahoma,"POLYGON ((-100.08771 37.00026, -94.61624 37.00...",Oklahoma,OK,3956971,2.731109e+05,14.488514
36,OR,Oregon,"POLYGON ((-123.21135 46.17414, -123.11824 46.1...",Oregon,OR,4217737,4.834828e+05,8.723655
37,PA,Pennsylvania,"POLYGON ((-79.76278 42.25265, -79.76278 42.000...",Pennsylvania,PA,12801989,2.045401e+05,62.589130
38,RI,Rhode Island,"MULTIPOLYGON (((-71.19684 41.67757, -71.12017 ...",Rhode Island,RI,1059361,4.772564e+03,221.968952
39,SC,South Carolina,"POLYGON ((-82.76414 35.06690, -82.55054 35.160...",South Carolina,SC,5148714,1.171631e+05,43.944843
40,SD,South Dakota,"POLYGON ((-104.04753 45.94411, -96.56056 45.93...",South Dakota,SD,884659,3.900544e+05,2.268040
41,TN,Tennessee,"POLYGON ((-88.05487 36.49638, -88.07130 36.677...",Tennessee,TN,6829174,1.659725e+05,41.146414
42,TX,Texas,"POLYGON ((-101.81294 36.50186, -100.00007 36.5...",Texas,TX,28995881,9.439132e+05,30.718802
43,UT,Utah,"POLYGON ((-112.16436 41.99523, -111.04706 42.0...",Utah,UT,3205958,3.664837e+05,8.747887
44,VT,Vermont,"POLYGON ((-71.50355 45.01303, -71.49260 44.914...",Vermont,VT,623989,4.774382e+04,13.069524
45,VA,Virginia,"MULTIPOLYGON (((-75.39766 38.01350, -75.24430 ...",Virginia,VA,8535519,1.673507e+05,51.003769
46,WA,Washington,"MULTIPOLYGON (((-117.03336 49.00024, -117.0443...",Washington,WA,7614893,3.814260e+05,19.964276
47,WV,West Virginia,"POLYGON ((-80.51860 40.63695, -80.51860 39.722...",West Virginia,WV,1792147,1.031074e+05,17.381365
48,WI,Wisconsin,"POLYGON ((-90.41543 46.56848, -90.22921 46.508...",Wisconsin,WI,5822434,2.861856e+05,20.344956
49,WY,Wyoming,"POLYGON ((-109.08084 45.00207, -105.91517 45.0...",Wyoming,WY,578759,4.726407e+05,1.224522